"""add attribute category.on_menu

Revision ID: 170fef33209b
Revises: 3a7b7274390f
Create Date: 2022-03-25 20:19:51.996748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170fef33209b'
down_revision = '3a7b7274390f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('on_menu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'on_menu')
    # ### end Alembic commands ###
